WORKDIR: ./shared
TICKET_PATH: ./shared/keys/ticket.txt
SSH_PUBLIC_KEY_PATH: ../.ssh/mba
REMOTE_HOST: marco@mba:/Users/Marco/shared
OUTPUT_PATH: ./shared/logs/output.log
PCAP_PATH: ./shared/pcap
TEST_CASES: test_cases.yaml




