version: "3.3"

services:

  client_1:
    image: pulltin/quiclab:2.0
    privileged: true
    hostname: client_1
    container_name: client_1
    volumes:
      - ./client/scripts/:/scripts
      - ./shared:/shared
      - ./shared/logs:/shared/logs
      - ./shared/keys:/shared/keys
      - ./shared/pcap:/shared/pcap
      - ./shared/qlog_client:/shared/qlog_client
      - ./shared/tcpprobe:/shared/tcpprobe
    cap_add:
      - NET_ADMIN
    networks:
      A_client_network:
        ipv4_address: 172.1.0.101
    environment:
      - TZ=Europe/Berlin
      - HOST=client_1
      - LOG_PATH=/shared/logs/client_1.log
      - KEYS_PATH=/shared/keys/client.key
      - TICKET_PATH=/shared/keys/ticket.txt
      - QLOG_PATH=/shared/qlog_client
      - PCAP_PATH=/shared/pcap/client_1.pcap
    stdin_open: true
    tty: true
    command: "/scripts/setup.sh"
    working_dir: /

  client_2:
    image: pulltin/quiclab:2.0
    privileged: true
    hostname: client_2
    container_name: client_2
    volumes:
      - ./client/scripts/:/scripts
      - ./shared:/shared
      - ./shared/logs:/shared/logs
      - ./shared/keys:/shared/keys
      - ./shared/pcap:/shared/pcap
      - ./shared/qlog_client:/shared/qlog_client
      - ./shared/tcpprobe:/shared/tcpprobe
    cap_add:
      - NET_ADMIN
    networks:
      A_client_network:
        ipv4_address: 172.1.0.102
    environment:
      - TZ=Europe/Berlin
      - HOST=client_2
      - LOG_PATH=/shared/logs/client_2.log
      - KEYS_PATH=/shared/keys/client.key
      - TICKET_PATH=/shared/keys/ticket.txt
      - QLOG_PATH=/shared/qlog_client
      - PCAP_PATH=/shared/pcap/client_2.pcap
    stdin_open: true
    tty: true
    command: "/scripts/setup.sh"
    working_dir: /

  # client_3:
  #   image: pulltin/quiclab:2.0
  #   privileged: true
  #   hostname: client_3
  #   container_name: client_3
  #   volumes:
  #     - ./client/scripts/:/scripts
  #     - ./shared:/shared
  #     - ./shared/logs:/shared/logs
  #     - ./shared/keys:/shared/keys
  #     - ./shared/pcap:/shared/pcap
  #     - ./shared/qlog_client:/shared/qlog_client
  #   cap_add:
  #     - NET_ADMIN
  #   networks:
  #     A_client_network:
  #       ipv4_address: 172.1.0.103
  #   environment:
  #     - TZ=Europe/Berlin
  #     - HOST=client_3
  #     - LOG_PATH=/shared/logs/client_3.log
  #     - KEYS_PATH=/shared/keys/client.key
  #     - TICKET_PATH=/shared/keys/ticket.txt
  #     - QLOG_PATH=/shared/qlog_client
  #     - PCAP_PATH=/shared/pcap/client_3.pcap
  #   stdin_open: true
  #   tty: true
  #   command: "/scripts/setup.sh"
  #   working_dir: /

  router_1:
    image: pulltin/quiclab:2.0
    privileged: true
    hostname: router_1
    container_name: router_1
    volumes:
      - ./router/scripts/:/scripts
      - ./shared:/shared
      - ./shared/logs:/shared/logs
      - ./shared/pcap:/shared/pcap
    cap_add:
      - NET_ADMIN
    networks:
      A_client_network:
        ipv4_address: 172.1.0.3
      B_wan_network:
        ipv4_address: 172.2.0.3
    environment:
      - TZ=Europe/Berlin
      - HOST=router_1
      - LOG_PATH=/shared/logs/router_1.log
      - PCAP_PATH_1=/shared/pcap/router_1_eth0.pcap
      - PCAP_PATH_2=/shared/pcap/router_1_eth1.pcap
      - SUBNET_1=172.2.0.0/24
      - SUBNET_2=172.3.0.0/24
      - GW_1=172.2.0.3
      - GW_2=172.2.0.4
      - IFACE=eth1

    command: "/scripts/setup.sh"
    stdin_open: true
    tty: true

  router_2:
    image: pulltin/quiclab:2.0
    privileged: true
    hostname: router_2
    container_name: router_2
    volumes:
      - ./router/scripts/:/scripts
      - ./shared:/shared
      - ./shared/logs:/shared/logs
      - ./shared/pcap:/shared/pcap
    cap_add:
      - NET_ADMIN
    networks:
      B_wan_network:
        ipv4_address: 172.2.0.4
      C_server_network:
        ipv4_address: 172.3.0.4
    environment:
      - TZ=Europe/Berlin
      - HOST=router_2
      - LOG_PATH=/shared/logs/router_2.log
      - PCAP_PATH_1=/shared/pcap/router_2_eth0.pcap
      - PCAP_PATH_2=/shared/pcap/router_2_eth1.pcap
      - SUBNET_1=172.1.0.0/24
      - SUBNET_2=172.2.0.0/24
      - GW_1=172.2.0.3
      - GW_2=172.2.0.4
      - IFACE=eth0

    command: "/scripts/setup.sh"
    stdin_open: true
    tty: true

  server:
    image: pulltin/quiclab:2.0
    privileged: true
    hostname: server
    container_name: server
    volumes:
      - ./server/scripts/:/scripts
      - ./server/data/:/data
      - ./shared:/shared
      - ./shared/logs:/shared/logs
      - ./shared/keys:/shared/keys
      - ./shared/pcap:/shared/pcap
      - ./shared/qlog_server:/shared/qlog_server
      - ./shared/tcpprobe:/shared/tcpprobe
    cap_add:
      - NET_ADMIN
    networks:
      C_server_network:
        ipv4_address: 172.3.0.5
    environment:
      - TZ=Europe/Berlin
      - HOST=server
      - LOG_PATH=/shared/logs/server.log
      - QLOG_PATH=/shared/qlog_server
      - PCAP_PATH=/shared/pcap/server.pcap

    command: "/scripts/setup.sh"
    stdin_open: true
    tty: true

  # server_2:
  #   image: pulltin/quiclab:2.0
  #   privileged: true
  #   hostname: server_2
  #   container_name: server_2
  #   volumes:
  #     - ./server/scripts/:/scripts
  #     - ./server/data/:/data
  #     - ./shared:/shared
  #     - ./shared/logs:/shared/logs
  #     - ./shared/keys:/shared/keys
  #     - ./shared/pcap:/shared/pcap
  #     - ./shared/qlog_server:/shared/qlog_server
  #   cap_add:
  #     - NET_ADMIN
  #   networks:
  #     C_server_network:
  #       ipv4_address: 172.3.0.6
  #   ports:
  #     - 6121:6121
  #   environment:
  #     - TZ=Europe/Berlin
  #     - HOST=server_2
  #     - LOG_PATH=/shared/logs/server.log
  #     - QLOG_PATH=/shared/qlog_server
  #     - PCAP_PATH=/shared/pcap/server_2.pcap
  #   command: "/scripts/setup.sh"
  #   stdin_open: true
  #   tty: true

  grafana:
    image: "grafana/grafana-oss:latest"
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      A_client_network:
        ipv4_address: 172.1.0.52
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=quiclab
      - GF_SECURITY_ADMIN_PASSWORD=quiclab
    restart: unless-stopped

  file_server:
    image: pulltin/quiclab:2.0
    container_name: file_server
    hostname: file_server
    ports:
      - "80:80"
    volumes:
      - ./server/scripts/:/scripts
      - ./shared:/shared
    command:
      - "/scripts/setup_file_server.sh"
    stdin_open: true
    tty: true

volumes:
  grafana-storage: {}
networks:
  A_client_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.1.0.0/24
  B_wan_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.2.0.0/24
  C_server_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.3.0.0/24
