version: "3.3"

services:
  client:
    image: pulltin/test_env:client
    hostname: client
    container_name: client
    volumes:
      - /root/test_env/shared:/shared
      - /root/test_env/shared/keys:/shared/keys
      - /root/test_env/shared/pcap:/shared/pcap
      - /root/test_env/shared/qlog:/shared/qlog
    cap_add:
      - NET_ADMIN
    networks:
      A_client_network:
        ipv4_address: 172.1.0.2 
    tty: true 
    command: "/setup.sh"
    working_dir: /

  router_1:
    image: pulltin/test_env:router_1
    hostname: router_1
    container_name: router_1
    volumes:
      - /root/test_env/shared:/shared
      - /root/test_env/shared/pcap:/shared/pcap
    cap_add:
      - NET_ADMIN
    networks:
      A_client_network:
        ipv4_address: 172.1.0.3
      B_wan_network:
        ipv4_address: 172.2.0.3 
    command: "/setup.sh"
    tty: true

  router_2:
    image: pulltin/test_env:router_2
    hostname: router_2
    container_name: router_2
    volumes:
      - /root/test_env/shared:/shared
      - /root/test_env/shared/pcap:/shared/pcap
    cap_add:
      - NET_ADMIN
    networks:
      B_wan_network:
        ipv4_address: 172.2.0.4
      C_server_network:
        ipv4_address: 172.3.0.4 
    command: "/setup.sh" 
    tty: true


  server:
    image: pulltin/test_env:server
    hostname: server
    container_name: server
    volumes:
      - /root/test_env/shared:/shared
      - /root/test_env/shared/keys:/shared/keys
      - /root/test_env/shared/pcap:/shared/pcap
      - /root/test_env/shared/qlog:/shared/qlog
    cap_add:
      - NET_ADMIN
    networks:
      C_server_network:
        ipv4_address: 172.3.0.5 
    command: "/setup.sh"
    tty: true


networks:
  A_client_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.1.0.0/24
  B_wan_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.2.0.0/24
  C_server_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.3.0.0/24

