version: "3.3"

services:
  client_aioquic_1:
    image: pulltin/test_env:amd64
    privileged: true  
    hostname: client_aioquic_1
    container_name: client_aioquic_1
    volumes:
      - ${ROOT_DIR}/test_env/client_aioquic_1/scripts/:/scripts/
      - ${ROOT_DIR}/test_env/shared:/shared
      - ${ROOT_DIR}/test_env/shared/logs:/shared/logs
      - ${ROOT_DIR}/test_env/shared/keys:/shared/keys
      - ${ROOT_DIR}/test_env/shared/pcap:/shared/pcap
      - ${ROOT_DIR}/test_env/shared/qlog_client:/shared/qlog_client
      - ${ROOT_DIR}/test_env/shared/tcpprobe:/shared/tcpprobe
    cap_add:
      - NET_ADMIN
    networks:
      A_client_network:
        ipv4_address: 172.1.0.101 
    environment:
      - TZ=Europe/Berlin
    tty: true 
    command: "/scripts/setup.sh"
    working_dir: /

  client_aioquic_2:
    image: pulltin/test_env:amd64
    privileged: true  
    hostname: client_aioquic_2
    container_name: client_aioquic_2
    volumes:
      - ${ROOT_DIR}/test_env/client_aioquic_2/scripts/:/scripts/
      - ${ROOT_DIR}/test_env/shared:/shared
      - ${ROOT_DIR}/test_env/shared/logs:/shared/logs
      - ${ROOT_DIR}/test_env/shared/keys:/shared/keys
      - ${ROOT_DIR}/test_env/shared/pcap:/shared/pcap
      - ${ROOT_DIR}/test_env/shared/qlog_client:/shared/qlog_client
      - ${ROOT_DIR}/test_env/shared/tcpprobe:/shared/tcpprobe
    cap_add:
      - NET_ADMIN
    networks:
      A_client_network:
        ipv4_address: 172.1.0.102
    environment:
      - TZ=Europe/Berlin
    tty: true 
    command: "/scripts/setup.sh"
    working_dir: /

  router_1:
    image: pulltin/test_env:amd64
    privileged: true  
    hostname: router_1
    container_name: router_1
    volumes:
      - ${ROOT_DIR}/test_env/router_1/scripts/:/scripts/
      - ${ROOT_DIR}/test_env/shared:/shared
      - ${ROOT_DIR}/test_env/shared/logs:/shared/logs
      - ${ROOT_DIR}/test_env/shared/pcap:/shared/pcap
    cap_add:
      - NET_ADMIN
    networks:
      A_client_network:
        ipv4_address: 172.1.0.3
      B_wan_network:
        ipv4_address: 172.2.0.3 
    environment:
      - TZ=Europe/Berlin
    command: "/scripts/setup.sh"
    tty: true

  router_2:
    image: pulltin/test_env:amd64
    privileged: true  
    hostname: router_2
    container_name: router_2
    volumes:
      - ${ROOT_DIR}/test_env/router_2/scripts/:/scripts/
      - ${ROOT_DIR}/test_env/shared:/shared
      - ${ROOT_DIR}/test_env/shared/logs:/shared/logs
      - ${ROOT_DIR}/test_env/shared/pcap:/shared/pcap
    cap_add:
      - NET_ADMIN
    networks:
      B_wan_network:
        ipv4_address: 172.2.0.4
      C_server_network:
        ipv4_address: 172.3.0.4 
    environment:
      - TZ=Europe/Berlin
    command: "/scripts/setup.sh" 
    tty: true


  server:
    image: pulltin/test_env:amd64
    privileged: true  
    hostname: server
    container_name: server
    volumes:
      - ${ROOT_DIR}/test_env/server/scripts/:/scripts/
      - ${ROOT_DIR}/test_env/server/data/:/data/
      - ${ROOT_DIR}/test_env/shared:/shared
      - ${ROOT_DIR}/test_env/shared/logs:/shared/logs
      - ${ROOT_DIR}/test_env/shared/keys:/shared/keys
      - ${ROOT_DIR}/test_env/shared/pcap:/shared/pcap
      - ${ROOT_DIR}/test_env/shared/qlog_server:/shared/qlog_server
      - ${ROOT_DIR}/test_env/shared/tcpprobe:/shared/tcpprobe
    cap_add:
      - NET_ADMIN
    networks:
      C_server_network:
        ipv4_address: 172.3.0.5 
    environment:
      - TZ=Europe/Berlin
    command: "/scripts/setup.sh"
    tty: true


networks:
  A_client_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.1.0.0/24
  B_wan_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.2.0.0/24
  C_server_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.3.0.0/24

